Treeofsavior/PortugueseTranslation

- QUEST_JOBSTEP_BP.tsv
Tradução efetuada, ficaram pendentes as linhas 23 e 48 pois fiquei na dúvida da melhor tradução.
Convencionei com [#pending texto] as traduções que ainda não foram definidas, como as de lugares e nomes de classes.
Referenciando a issue #2
> Quest_Jobstep - Linhas 1 à 50

- QUEST_BP.tsv
Translated Line 1 to 100. Except Line 27.
> Lines 1-100 QuestBP

- QUEST_BP.tsv
> Update Lines 152-250 QUEST_BP.tsv

- QUEST_BP.tsv
Translated line 501 till line 550.
> Update QUEST_BP.tsv [Lines 501-550]

- QUEST_LV_0100_BP.tsv
I let the names of the places untranslated for now to avoid any problem.
Deixei os nomes dos lugares sem traduzir por enquanto para evitar qualquer problema.
> QUEST_LV_0100_BP lines 01 to 20

- QUEST_JOBSTEP_BP.tsv
- Translated lines 51 until 99
- Updated master names with conventions defined at wiki.
issue #54
> PR for issue #54

- UI_BP.tsv
> UI_BP.tsv UI_20150317_001101 to UI_20150317_001250

- SKILL_BP.tsv
Well, Let's start the Skills of the game.
First 150 lines.
> Update SKILL_BP.tsv SKILL_20150317_000001 to SKILL_20150317_000150

- SKILL_BP.tsv
> Update SKILL_BP.tsv SKILL_20150317_000301 to SKILL_20150317_000450

- QUEST_BP.tsv
Ok, I did the line 1051 till line 1138. It's a complete story inside the game lore. A beautiful and moving one indeed. It was a heavy one to translate, so i hope you guys can read it carefully and check if there is any mistakes or typos. There is a lot of 'pending' words too that we are waiting till we decide the best translation. Thank you guys.
> QUEST_BP.tsv [Lines1051-1138]

- QUEST_BP.tsv
QUEST_BP
Linhas 751 até 900.
Lines 751 to 900.
> QUEST_BP 751 - 900

- SKILL_BP.tsv
Here is the next part.
-----
Novamente criei alguns nomes que não tinha como deixar o original e outra vez peço para que chequem as mudança, abaixo colocarei os nomes, aceito idéia melhores:
Shadow Clone - Clone Sombrio (cheguei a pensar em clone das sombras)
Sleep - Sono
Surespell - Conjuração Perfeita
Hell Breath - Sopro Infernal
Ice Bolt - Lanças de Gelo
Ice Blast - Explosão Gelada
Swap - Trocar
Raise - Levantar
Hangman's Knot - Entrelaçar
Stone Curse - Petrificar
Nomes que não conseguir pensar em algo:
Efeito: Paering (não encontrei tradução para este efeito e também não sei o que este efeito faz)
> Update SKILL_BP.tsv SKILL_20150317_001051 to SKILL_20150317_001200

- QUEST_LV_0100_BP.tsv
For now the player is referred as male.
> QUEST_LV_0100_BP.tsv lines 21 to 100

- UI_BP.tsv
> UI_BP.tsv UI_20150317_000501 to UI_20150317_000650

- UI_BP.tsv
> UI_BP.tsv UI_20150317_001701 to UI_20150317_001831

- SKILL_BP.tsv
> Update SKILL_BP.tsv SKILL_20150317_000151 to SKILL_20150317_000300

- SKILL_BP.tsv
> Update SKILL_BP.tsv SKILL_20150317_000451 to SKILL_20150317_000600

- QUEST_BP.tsv
Solicito revisão na linha 358, aonde diz:
'Is something buried under that grass?'
> Linhas 352 - 360 traduzidas

- SKILL_BP.tsv
Well, there we go, we finally started the classes skills. :D 
-------
Tive problemas para decidir nomes e alguns eu acabei não mudando por falta de idéia, segue a lista:
Nomes modificados: (aceito idéias melhores)
---------
Cartar Stroke - Pulverizar
Crown - Trauma
Bash - Golpe
High Guard - Aprimorar Defesa
Sttabing - Perfuração
Synchro Thrusting - Estocada Sincronizada
Shield Charge - Avançar
Earth Wave - Tremor  (Tbm pensei em "terremoto")
Steed Charge - Avanço Forçado (Tbm pensei em "Avanço Montado")
Doom Spike - Estocada Fatal
Rush - Corrida
Dragging Death - Trazendo a Morte (tbm pensei em "chegar da morte")
Stompping Kick - Chute e Pisoteio (Juro que tbm pensei "Vuadora" xD)
Wedge Formation - Formação em Pinça
Deeds of Valor - Ações de Bravura
Pain Barrier - Vigor
Double Pay Earn - …
> Update SKILL_BP.tsv SKILL_20150317_000901 to SKILL_20150317_001050

- QUEST_LV_0100_BP.tsv
Closes #146
Minha tradução das linhas 201-250
> QUEST_LV_0100_BP Lines 201-250

- SKILL_BP.tsv
IMC Games, check this first: http://imgur.com/wFXDgNZ
--------
Muito bem, mais 150 linhas das skills, vejam se está bom, novamente mudei alguns nomes de skills, se tiverem alguma idéia melhor, deixem ai.
> Update SKILL_BP.tsv SKILL_20150317_001201 to SKILL_20150317_001350

- UI_BP.tsv
> Fixed broken syntax on UI_BP.tsv LINE 519.

- SKILL_BP.tsv
> Update SKILL_BP.tsv Just few corrections.

- SKILL_BP.tsv
> Update SKILL_BP_005600 a 005700.tsv

- QUEST_JOBSTEP_BP.tsv
Add translation: line 131 to 231
EDIT: fixed a would be indent on line 210, sorry about that. Good to merge.
> Translated QUEST_JOBSTEP_BP.tsv lines 131 to 231

- QUEST_BP.tsv
Some quests from Fedimian (I guess).
I didn't know a better translation for "Wagon Carrier", change it if you have another idea.
> Update QUEST_BP.tsv QUEST_20150317_000587 to QUEST_20150317_000637

- QUEST_LV_0300_BP.tsv
QUEST_LV_0300_20150323_000001 to QUEST_LV_0300_20150717_000030
QUEST_LV_0300_20150323_000001 até QUEST_LV_0300_20150717_000030
ps: pretendo terminar até QUEST_LV_0300_20150717_000100
I intend to do till QUEST_LV_0300_20150717_000100
> Lines 1 to 30

- QUEST_BP.tsv
Replacing [space] with [tab] that didn't exist before each translation.
> UPDATE QUEST - Fixing tabs (part 1) - Lines 1 - 195

- QUEST_BP.tsv
There are many missing [tabs] at the beginning of each sentence, so I'm adding them now. A total of  346 lines were changed.
Only [spaces] were replaced by [tabs].
> UPDATE QUEST_BP.tsv - Adding missing tabs

- ETC_BP.tsv
- ITEM_BP.tsv
- QUEST_JOBSTEP_BP.tsv
- QUEST_LV_0100_BP.tsv
- QUEST_LV_0300_BP.tsv
- SKILL_BP.tsv
I organized each file fixing each wrong tab, that some times had a [space][tab] or [tab][tab] or [space] instead of [tab] before each sentence.
> UPDATE - [tab] fix for every file that had errors

- SKILL_BP.tsv
> Update SKILL_BP_5500 a 5600.tsv
